### PR TITLE
R6ast

### PR DESCRIPTION
**Pull request by dirkschumacher**

### CODE REVIEW

**Comment by dirkschumacher** [comment]
YOLO

**Comment by coatless** [comment]
Nice reorganization. Best part is the set once environments. 

Though, using R6 classes is the new way forward?

https://github.com/dirkschumacher/armacmp/pull/10/files#diff-0a697d7b31f70446ff63b0be98d42f29

**Comment by coatless** [comment]
Also, is there anyway I could get you to split off the `pkgdown` website into a separate branch instead of adding to the master branch? 

c.f. https://pkgdown.r-lib.org/reference/deploy_site_github.html

**Comment by dirkschumacher** [comment]
> Nice reorganization. Best part is the set once environments.
> 
> Though, using R6 classes is the new way forward?
> 
> https://github.com/dirkschumacher/armacmp/pull/10/files#diff-0a697d7b31f70446ff63b0be98d42f29

I wanted references for the pointers to parents/scopes in the AST so I thought `R6` might work and just implemented it. So far it looks ok and might be a viable approach.

**Comment by dirkschumacher** [comment]
> Also, is there anyway I could get you to split off the `pkgdown` website into a separate branch instead of adding to the master branch?
> 
> c.f. https://pkgdown.r-lib.org/reference/deploy_site_github.html

Yeah. Good idea. See #12

**Comment by coatless** [comment]
Also, in the `README`-post update, these lines should be removed:

https://github.com/dirkschumacher/armacmp/blob/119c4ed848c03e8987fed3a1c27a55160ba1e434/README.Rmd#L84-L87

**Comment by dirkschumacher** [comment]
Thanks. Done.

**Pull request merged**
